#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --quiet -- "frontend/"
then
    echo "Detected no change from frontend"
    exit 0
else
    echo "Detected change from frontend Changed"
    echo '🏗️👷 Styling, testing and building your project before committing'

    # Check Prettier standards
    cd frontend && npm run check-format ||
    (
        echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
        false;
    )

    # Check ESLint Standards
    npm run check-lint ||
    (
            echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
            false; 
    )

    # Check tsconfig standards
    npm run check-types ||
    (
        echo 'Are you seriously trying to write that? Make the changes required above.'
        false;
    )

    # If everything passes... Now we can commit
    echo 'Passed format, lint and type checks. Commiting...'
fi

