#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --quiet -- "frontend/"
then
    exit 0
else
    echo "Detected change from frontend Changed"
    echo '🏗️👷 Styling, testing and building your project before committing'

    # Check ESLint Standards
    cd frontend && npm run check-lint ||
    (
            echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
            false; 
    )

    # Check tsconfig standards
    npm run check-types ||
    (
        echo 'TypeScript Check Failed. Make the changes required above.'
        false;
    )

    # Check Prettier standards
     npm run format ||
    (
        echo 'Prettier Formatting Failed. Run npm run check-format to view the format errors.';
        false;
    )

    # If everything passes... Now we can commit
    echo 'Passed lint and type checks and formatted code. Commiting...'
fi

