version: "3.8"
services:
  frontend:
    profiles:
      - main
      - fe
    build:
      context: frontend
    ports:
      - "3000:3000"
    env_file: /frontend/.env.local
    environment:
      - NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}

  backend:
    ports:
      - "8080:8080"
    profiles:
      - main
      - be
    build:
      context: backend
    env_file: .env
    environment:
      - MONGO_URI=${MONGO_URI}

  postgres:
    profiles:
      - main
      - be
      - be-seed
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flowforge_db

  mongo:
    profiles:
      - main
      - be
      - be-seed
    image: mongo:7.0
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=flowforge_db

  mongo_seed:
    profiles:
      - be-seed
    build:
      context: backend
      dockerfile: dockerfiles/mongo_seed.Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
