version: "3.8"
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flowforge_db
