name: Backend Tests
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "backend/**"

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
      - name: Install dependencies
        run: go mod download
        working-directory: backend
      - name: Test with the Go CLI
        run: go test ./...
        working-directory: backend
