name: Backend Tests
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "backend/**"

jobs:
  go-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
      - name: Verify dependencies
        run: go mod verify
        working-directory: backend
      - name: Build
        run: go build -v ./...
        working-directory: backend
      - name: Test
        run: go test ./...
        working-directory: backend
