name: Go Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
        working-directory: backend
      - name: Test with the Go CLI
        run: go test ./...
        working-directory: backend
